@Ledger = http://localhost:3001

POST {{Ledger}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "email": "ivan.ivanov@gmail.com",
  "password": "test123"
}

###

POST {{Ledger}}/api/auth/login
Content-Type: application/json

{
  "email": "ivan.ivanov@gmail.com",
  "password": "test123"
}

> {%
    client.global.set("auth_token", response.body.token)
%}

###

GET {{Ledger}}/api/auth/me
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

GET {{Ledger}}/api/equipment
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

POST {{Ledger}}/api/equipment
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "STEM 1 Laptop No. 2",
  "type": "Laptop",
  "serialNumber": "SKS-2525",
  "condition": "napulno razrushen",
  "location": "UKTC",
  "photoUrl": "",
  "requiresAdminApproval": true
}

###

GET {{Ledger}}/api/equipment/3973c348-b990-4670-b032-f6fd0b0c8065
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

DELETE {{Ledger}}/api/equipment/3973c348-b990-4670-b032-f6fd0b0c8065
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

GET {{Ledger}}/api/users
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###